SVG = "http://www.w3.org/2000/svg"
XHTML = "http://www.w3.org/1999/xhtml"
INKFLOW = "urn:inkflow"
INKSCAPE = "http://www.inkscape.org/namespaces/inkscape"
SODIPODI = "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"

INKFLOW_PARENT = f"{{{INKFLOW}}}parent"
INKFLOW_DEFAULT_ZONE = f"{{{INKFLOW}}}default-zone"
INKFLOW_LAYOUT_SRC = f"{{{INKFLOW}}}layout-src"
INKFLOW_LAYOUT_HASH = f"{{{INKFLOW}}}layout-hash"
