name: Docs

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4

      - run: uv sync --group docs

      - run: uv run inkflow build --deck demo/deck.py --output docs/demo

      - run: uv run inkflow build --deck src/inkflow/theme/showcase/deck.py --output docs/built-in-theme/presentation

      - run: uv run mkdocs build --strict
